services:
  postgres:  # Основной сервис БД
    image: postgres:15-alpine
    container_name: bank-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-bank}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate:v4.16.2
    container_name: bank-migrate
    command:
      - "-path=/migrations"
      - "-database=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-bank}?sslmode=disable"
      - "up"
    volumes:
      - ./migrations:/migrations
    depends_on:
      postgres:  # Должно совпадать с именем основного сервиса
        condition: service_healthy
  api:  # Основной сервис приложения
    build: .
    container_name: bank-api
    env_file: .env  
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-bank}
      JWT_SECRET: ${JWT_SECRET:-secret}
    ports:
      - "8080:8080"
    depends_on:
      migrate:
        condition: service_completed_successfully  

volumes:
  postgres_data:
